### ISSUE TITLE
Is this implementation vulnerable to splicing attacks?

### ISSUE THREAD

**Issue by copumpkin** [adjoint-io/merkle-tree#2]
I was poking around your implementation and noticed that the tree doesn't seem to consider "leafness" (or tree depth more generally) when computing a node's hash, which at a superficial glance suggests it might be vulnerable to an issue like this:

https://github.com/zcash/zcash/issues/404

Where you can basically replace a subtree with a leaf of a particular hash. If you have invariants forcing tree depth or other checks in place, it's obviously not an issue. Obviously not 100% sure this implementation suffers from it, but I figured I'd ask just in case

**Comment by sdiehl** [comment]
Probably not.

**Comment by copumpkin** [comment]
(For anyone finding this in the future)

I see now that leaves get hashed with a 0 prepended to the contents and inner nodes get a 1 on them, which prevents that kind of bug:

https://github.com/adjoint-io/merkle-tree/blob/a5ac8028c0b11d8546f2b94a37fc5246f94cf764/src/Crypto/Hash/MerkleTree.hs#L143-L144

https://github.com/adjoint-io/merkle-tree/blob/a5ac8028c0b11d8546f2b94a37fc5246f94cf764/src/Crypto/Hash/MerkleTree.hs#L154-L156
